[package]
name = "engram_gba"
version = "0.1.12"
edition = "2024"
authors = ["Donisha Smith <donishasmith@outlook.com>"]
license-file = "LICENSE"

[dependencies]
chrono.workspace = true
egui.workspace = true
egui-macroquad.workspace = true
egui_plot.workspace = true
macroquad.workspace = true
shared.workspace = true
