[package]
name = "frontend"
version = "0.1.26"
edition = "2024"

[[bin]]
name = "engram"
path = "src/main.rs"

[dependencies]
shared.workspace = true
gb.workspace = true
gba.workspace = true
egui.workspace = true
egui-macroquad.workspace = true
rfd.workspace = true
macroquad.workspace = true
gilrs.workspace = true
egui-notify.workspace = true
mlua.workspace = true
