[package]
name = "engram_gb"
version = "0.1.13"
edition = "2024"
authors = ["Donisha Smith <donishasmith@outlook.com>"]
license-file = "LICENSE"

[dependencies]
shared.workspace = true
chrono.workspace = true
macroquad.workspace = true

[dev-dependencies]
serde.workspace = true
serde_json.workspace = true
