use crate::input::Bindings;
use gilrs::Button;
use macroquad::input::KeyCode;

// taken straight from miniquad and used regex because no way could i type this all out
// https://github.com/not-fl3/miniquad/blob/master/src/native/wasm/keycodes.rs
pub const BINDABLE_KEYS: [KeyCode; 117] = [
    KeyCode::Space,
    KeyCode::Apostrophe,
    KeyCode::Comma,
    KeyCode::Minus,
    KeyCode::Period,
    KeyCode::Slash,
    KeyCode::Key0,
    KeyCode::Key1,
    KeyCode::Key2,
    KeyCode::Key3,
    KeyCode::Key4,
    KeyCode::Key5,
    KeyCode::Key6,
    KeyCode::Key7,
    KeyCode::Key8,
    KeyCode::Key9,
    KeyCode::Semicolon,
    KeyCode::Equal,
    KeyCode::A,
    KeyCode::B,
    KeyCode::C,
    KeyCode::D,
    KeyCode::E,
    KeyCode::F,
    KeyCode::G,
    KeyCode::H,
    KeyCode::I,
    KeyCode::J,
    KeyCode::K,
    KeyCode::L,
    KeyCode::M,
    KeyCode::N,
    KeyCode::O,
    KeyCode::P,
    KeyCode::Q,
    KeyCode::R,
    KeyCode::S,
    KeyCode::T,
    KeyCode::U,
    KeyCode::V,
    KeyCode::W,
    KeyCode::X,
    KeyCode::Y,
    KeyCode::Z,
    KeyCode::LeftBracket,
    KeyCode::Backslash,
    KeyCode::RightBracket,
    KeyCode::Apostrophe,
    KeyCode::Escape,
    KeyCode::Enter,
    KeyCode::Tab,
    KeyCode::Backspace,
    KeyCode::Insert,
    KeyCode::Delete,
    KeyCode::Right,
    KeyCode::Left,
    KeyCode::Down,
    KeyCode::Up,
    KeyCode::PageUp,
    KeyCode::PageDown,
    KeyCode::Home,
    KeyCode::End,
    KeyCode::CapsLock,
    KeyCode::ScrollLock,
    KeyCode::NumLock,
    KeyCode::PrintScreen,
    KeyCode::Pause,
    KeyCode::F1,
    KeyCode::F2,
    KeyCode::F3,
    KeyCode::F4,
    KeyCode::F5,
    KeyCode::F6,
    KeyCode::F7,
    KeyCode::F8,
    KeyCode::F9,
    KeyCode::F10,
    KeyCode::F11,
    KeyCode::F12,
    KeyCode::F13, // wait do keyboards with f keys greater than 12 actually exist
    KeyCode::F14,
    KeyCode::F15,
    KeyCode::F16,
    KeyCode::F17,
    KeyCode::F18,
    KeyCode::F19,
    KeyCode::F20,
    KeyCode::F21,
    KeyCode::F22,
    KeyCode::F23,
    KeyCode::F24,
    KeyCode::Kp0,
    KeyCode::Kp1,
    KeyCode::Kp2,
    KeyCode::Kp3,
    KeyCode::Kp4,
    KeyCode::Kp5,
    KeyCode::Kp6,
    KeyCode::Kp7,
    KeyCode::Kp8,
    KeyCode::Kp9,
    KeyCode::KpDecimal,
    KeyCode::KpDivide,
    KeyCode::KpMultiply,
    KeyCode::KpSubtract,
    KeyCode::KpAdd,
    KeyCode::KpEnter,
    KeyCode::KpEqual,
    KeyCode::LeftShift,
    KeyCode::LeftControl,
    KeyCode::LeftAlt,
    KeyCode::LeftSuper,
    KeyCode::RightShift,
    KeyCode::RightControl,
    KeyCode::RightAlt,
    KeyCode::RightSuper,
    KeyCode::Menu,
];

pub const BINDABLE_BUTTONS: [Button; 18] = [
    Button::DPadDown,
    Button::DPadLeft,
    Button::DPadRight,
    Button::DPadUp,
    Button::East,
    Button::LeftThumb,
    Button::LeftTrigger,
    Button::LeftTrigger2,
    Button::Mode,
    Button::North,
    Button::RightThumb,
    Button::RightTrigger,
    Button::RightTrigger2,
    Button::Select,
    Button::South,
    Button::Start,
    Button::West,
    Button::Z,
];

pub const DEFAULT_HOT_KEYS: [Bindings; 4] = [
    Bindings {
        label: "Screenshot",
        key: KeyCode::F7,
        button: None,
    },
    Bindings {
        label: "Lua",
        key: KeyCode::F8,
        button: None,
    },
    Bindings {
        label: "Debugger",
        key: KeyCode::F11,
        button: None,
    },
    Bindings {
        label: "Gif",
        key: KeyCode::F12,
        button: None,
    },
];

pub const DEFAULT_GBA_KEYS: [Bindings; 10] = [
    Bindings {
        label: "Up",
        key: KeyCode::W,
        button: Some(Button::DPadUp),
    },
    Bindings {
        label: "Left",
        key: KeyCode::A,
        button: Some(Button::DPadLeft),
    },
    Bindings {
        label: "Down",
        key: KeyCode::S,
        button: Some(Button::DPadDown),
    },
    Bindings {
        label: "Right",
        key: KeyCode::D,
        button: Some(Button::DPadRight),
    },
    Bindings {
        label: "A",
        key: KeyCode::L,
        button: Some(Button::East),
    },
    Bindings {
        label: "B",
        key: KeyCode::K,
        button: Some(Button::South),
    },
    Bindings {
        label: "Start",
        key: KeyCode::Enter,
        button: Some(Button::Start),
    },
    Bindings {
        label: "Select",
        key: KeyCode::RightShift,
        button: Some(Button::Select),
    },
    Bindings {
        label: "R",
        key: KeyCode::I,
        button: Some(Button::RightTrigger),
    },
    Bindings {
        label: "L",
        key: KeyCode::O,
        button: Some(Button::LeftTrigger),
    },
];
