[package]
name = "shared"
version = "0.1.15"
edition = "2024"
authors = ["Donisha Smith <donishasmith@outlook.com>"]
license-file = "LICENSE"

[dependencies]
cpal.workspace = true
macroquad.workspace = true
egui.workspace = true
rtrb.workspace = true
gif.workspace = true
chrono.workspace = true
rfd.workspace = true
dirs.workspace = true
toml.workspace = true
serde.workspace = true
egui_code_editor.workspace = true
mlua.workspace = true
